name: builder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../shared/dependencies
  core:
    path: ../core
  home:
    path: ../modules/home
  digital_account:
    path: ../shared/services/digital_account
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true